export const cities: string[] = [
  "London, UK",
  "Manchester, UK",
  "Birmingham, UK",
  "Glasgow, UK",
  "Liverpool, UK",
  "Edinburgh, UK",
  "Bristol, UK",
  "Leeds, UK",
  "Sheffield, UK",
  "Newcastle upon Tyne, UK",
  "Cardiff, UK",
  "Belfast, UK",
  "Nottingham, UK",
  "Southampton, UK",
  "Aberdeen, UK",
  "Coventry, UK",
  "Leicester, UK",
  "Reading, UK",
  "Bournemouth, UK",
  "Brighton, UK",
  "Plymouth, UK",
  "Swansea, UK",
  "Oxford, UK",
  "Cambridge, UK",
  "York, UK",
  "Norwich, UK",
  "Dundee, UK",
  "Exeter, UK",
  "Cheltenham, UK",
  "Swindon, UK",
  "Derby, UK",
  "Blackpool, UK",
  "Milton Keynes, UK",
  "Doncaster, UK",
  "Guildford, UK",
  "Stoke-on-Trent, UK",
  "Lincoln, UK",
  "Wolverhampton, UK",
  "Worcester, UK",
  "Hull, UK",
  "Derry,UK",
];
